### ISSUE TITLE
 使用inputView.updateNumber传入7位车牌号码时候最后一位不显示

### ISSUE THREAD

**Issue by fx4758** [parkingwang/vehicle-keyboard-android#14]

**Comment by yoojia** [comment]
可否描述详细的一些情况呢？似乎未能复现

**Comment by yoojia** [comment]
我想你的问题，应该是在KeyView还没有完成显示出来前，就调用了UpdateNumber()来显示。一般情况下，需要在Activity.onResume / Fragment.onResume 等函数回调中调用 UpdateNumber()函数。

**Comment by fx4758** [comment]
我尝试把UpdateNumber放在onResume中，结果还是少传一位，0.4.0版本是OK的。
主要代码如下：

`
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        popupKeyboard = new PopupKeyboard(this);
        popupKeyboard.attach(inputView, this);
    }
`
`
  protected void onResume() {
        super.onResume();
       if (!TextUtils.isEmpty(receiveCarNO)) {
            inputView.updateNumber(receiveCarNO);
        }
    }
`

**Comment by fx4758** [comment]
0.5.3版本传值少一位，0.4.0版本在onCreate里面调用UpdateNumber是OK的

**Comment by yoojia** [comment]
你尝试使用Handler.postDelay()来延时几毫秒看看能否解决。我在下一个版本里增加一个更新号码缓存的处理。

**Comment by fx4758** [comment]
我在onResume()里面延迟20毫秒加载UpdateNumber后传入值就是完整的

**Comment by yoojia** [comment]
感谢你的反馈，问题应该就是View没有完成渲染前UpdateNumber的问题。
