### ISSUE TITLE
普通车牌最后一位可能是文字的

### ISSUE THREAD

**Issue by JakeWoki** [parkingwang/vehicle-keyboard-android#18]
正则：
`"([京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领A-Z]{1}[A-Z]{1}(([0-9]{5}[DF])|([DF]([A-HJ-NP-Z0-9])[0-9]{4})))" + "|([京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领A-Z]{1}[A-Z]{1}[A-HJ-NP-Z0-9]{4}[A-HJ-NP-Z0-9挂学警港澳领]{1})";`

**Comment by yoojia** [comment]
没有明白你所问的问题是什么意思呢。如果是校验车牌规则，使用正则表达式想要完全校验车牌号码的规则在复杂，不如用代码直接校验。

**Comment by msdx** [comment]
@JakeWoki 最后一位可能是文字的“学警挂试超领”的一位，这在本组件中也同样支持。另外最后一位为“港”或“澳”的前提条件是首位为“粤”，这在车牌键盘组件中同样支持。
