### ISSUE TITLE
点击键盘确定按钮没效果

### ISSUE THREAD

**Issue by caixiquan** [parkingwang/vehicle-keyboard-android#29]
点击键盘按钮的确定是在哪实现的？还有如何获取到输入的车牌号码

**Comment by ContextDong** [comment]
1.关于确定键
 mPopupKeyboard.getController().addOnInputChangedListener(new OnInputChangedListener(){
            @Override
            public void onChanged(String number, boolean isCompleted) {
                //当输入框的车牌号码发生变化时，回调此方法。
            }

            /**
             * 当车牌号码被输入完成后，调用此方法。
             * @param number 完整输入的车牌号码
             * @param isAutoCompleted 当前的输入完成状态，是否属于自动完成。
             *                        输入完成状态有两种：
             *                          1. 从部分车牌一直输入，直到输完最后一位时，会触发自动完成回调。此时isAutoCompleted为True。
             *                          2. 通过点击“确定”按键来触发输入完成。此时isAutoCompleted为False。
             */
            @Override
            public void onCompleted(String number, boolean isAutoCompleted) {

            }
        });

2.获取输入的车牌号码：InputView中有对应的api  ->  String getNumber()

**Comment by msdx** [comment]
感谢 @caixiquan 的解答。
