### ISSUE TITLE
建议增加键盘收回的按钮

### ISSUE THREAD

**Issue by baidonghui** [parkingwang/vehicle-keyboard-android#31]
目前已经可以做到车牌输入完整后调dismiss隐藏键盘，但是如果误触InputView，键盘弹起必须输入一下才能隐藏，希望在键盘上增加隐藏的按钮。

**Comment by msdx** [comment]
@baidonghui 监听键盘输入回调，在输入完成时隐藏键盘。
如果点击了InputView（不管是否为误触，视为要修改）弹出键盘，但不需要输入的话，直接点确定，会回调到键盘输入完成。

**Comment by GirlFriendNotFind** [comment]
@msdx 但是确定按钮必须输入完才能点击，点击了InputView但又想先填其他项，键盘无法通过确定隐藏
