### ISSUE TITLE
设置组件宽度，车牌输入框并未按比例缩放，导致显示变形

### ISSUE THREAD

**Issue by smallsquareface** [parkingwang/vehicle-keyboard-android#56]
我已确认所提问题在 FAQ.md 及 Issues 上没有。

问题描述：
设置组件宽度，车牌输入框并未按比例缩放，导致显示变形

车牌组件版本：
implementation 'com.parkingwang:keyboard:0.7.3'

Android 版本：
*

设备型号：
*

界面问题如下：
设置一个相对较小的组件宽度，导致每一个输入框宽度不一致，同时最后一项选中框也会显示不全

异常日志如下：

**Comment by smallsquareface** [comment]
> 
> 
> 我已确认所提问题在 FAQ.md 及 Issues 上没有。
> 
> 问题描述：
> 设置组件宽度，车牌输入框并未按比例缩放，导致显示变形
> 
> 车牌组件版本：
> implementation 'com.parkingwangkeyboard0.7.3'
> 
> Android 版本：
> *
> 
> 设备型号：
> *
> 
> 界面问题如下：
> 设置一个相对较小的组件宽度，导致每一个输入框宽度不一致，同时最后一项选中框也会显示不全
> 
> 异常日志如下：

**Comment by keluokeda** [comment]
老哥你是怎么解决的啊
我现在是文字显示不全
