### ISSUE TITLE
新版本能上传一下jcenter()吗？看着有新版本用不成，着急啊

### ISSUE THREAD

**Issue by huaxuanHan** [parkingwang/vehicle-keyboard-android#58]
我已确认所提问题在 FAQ.md 及 Issues 上没有。

问题描述：

车牌组件版本：
Android 版本：
设备型号：
界面问题如下：

异常日志如下：

**Comment by smallTrong** [comment]
直接因GitHub不行么      implementation 'com.github.parkingwang:vehicle-keyboard-android:0.7.6'

**Comment by smallTrong** [comment]
直接因GitHub不行么      implementation 'com.github.parkingwang:vehicle-keyboard-android:0.7.6'
