### ISSUE TITLE
系统键盘同时出现

### ISSUE THREAD

**Issue by huangjide** [parkingwang/vehicle-keyboard-android#7]
如果页面还有其他输入框让系统软键盘弹出来，那么这个键盘和系统键盘会同时上下显示出来，如何控制比较好呢？

**Comment by yoojia** [comment]
在点击车牌输入框时显示，输入完成后隐藏。

**Comment by YXHTom** [comment]
其他输入框还没有完全隐藏，这个键盘就出来了导致显示位置错乱，有什么建议吗

**Comment by YXHTom** [comment]
![1521707605919](https://user-images.githubusercontent.com/13691163/37759522-d23e11be-2dee-11e8-8b68-59d75548bfbf.jpg)

**Comment by msdx** [comment]
@YXHTom 你是使用哪种方式弹出键盘的？

**Comment by YXHTom** [comment]
edittext输入完成后隐藏系统输入框，后开启车牌输入框；系统输入框还没完全消失，车牌输入框就开始显示

**Comment by msdx** [comment]
@YXHTom 是使用PopupWindow来弹键盘的吗？

**Comment by YXHTom** [comment]
点击输入框自动单出来的键盘

**Comment by msdx** [comment]
@yoojia 抽时间更新一下。
`https://github.com/parkingwang/vehicle-keyboard-android/blame/master/keyboard/src/main/java/com/parkingwang/vehiclekeyboard/support/PopupHelper.java`，这个文件 69 行需要的 `bottom` 值计算需要改一下，如果 `windowSoftInputMode` 值为 `adjustPan` 或 `adjustNothing` 则为0。

```java
public enum AdjustInputMode {
    PAN {
        @Override
        public int calcOffsetY(View decorView) {
            return 0;
        }
    },
    RESIZE,
    NOTHING {
        @Override
        public int calcOffsetY(View decorView) {
            return 0;
        }
    },
    UNSPECIFIED;

    public int calcOffsetY(View decorView) {
        final Rect rect = new Rect();
        decorView.getWindowVisibleDisplayFrame(rect);
        return decorView.getHeight() - rect.bottom;
    }
}
```

**Comment by msdx** [comment]
@yoojia 请 review 一下 PR。
